# Generated by Django 5.2.1 on 2025-05-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя и фамилию', max_length=50, verbose_name='Имя и Фамилия')),
                ('message', models.TextField(blank=True, help_text='Введите ваше сообщение', null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['name', 'message'],
            },
        ),
    ]
