# Generated by Django 5.2.1 on 2025-05-23 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите содержимое', verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фотографию', null=True, upload_to='images/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Введите дату создания', verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['views'],
            },
        ),
    ]
